src/Web/ColorMix.Web/Areas/Administration/Controllers/AdminOrdersController.cs
using System;
using ColorMix.Services.DataServices.Contracts;
using ColorMix.Services.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ColorMix.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    [Authorize(Roles = "Admin")]
    public class AdminOrdersController : AdminController
    {
        private readonly IOrdersService ordersService;

        public AdminOrdersController(IOrdersService ordersService)
        {
            this.ordersService = ordersService;
        }

        public IActionResult AllOrders()
        {
            var sendOrders = this.ordersService.GetAllSendOrders();

            return this.View(sendOrders);
        }

        public IActionResult SendOrder(Guid orderId)
        {
            if (!this.ordersService.OrderExists(orderId))
            {
                return View("Error", new ErrorViewModel() { Message = ERROR });
            }

            this.ordersService.SendOrder(orderId);

            return this.RedirectToAction("AllOrders");
        }
    }
}

src/Web/ColorMix.Web/Controllers/CartController.cs
using System;
using ColorMix.Data.Models;
using ColorMix.Services.DataServices.Contracts;
using ColorMix.Services.Models;
using ColorMix.Services.Models.Products;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ColorMix.Web.Controllers
{
    public class CartController : BaseController
    {
        private readonly ICartService cartService;
        private readonly IProductService productService;
        private readonly UserManager<ColorMixUser> userManager;

        public CartController(ICartService cartService, IProductService productService, UserManager<ColorMixUser> userManager)
        {
            this.cartService = cartService;
            this.productService = productService;
            this.userManager = userManager;
        }
        
        public IActionResult Index()
        {
            var userId = this.userManager.GetUserId(this.User);

            var products = this.cartService.GetAllCartProducts(this.HttpContext.Session, userId);

            return this.View(products);
        }

        [HttpPost]
        public IActionResult AddToCart(DetailsViewModel model)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, ERROR);

                return this.RedirectToAction("Details", "Products");
            }

            this.cartService.AddToCart(model, this.HttpContext.Session, userId);

            return this.RedirectToAction("Index");
        }

        public IActionResult Remove(Guid id)
        {
            if (!this.productService.CheckIfProductExists(id))
            {
                return View("Error", new ErrorViewModel() { Message = ERROR });
            }
            
            this.cartService.Remove(id, this.HttpContext.Session, this.User);
            
            return this.RedirectToAction("Index");
        }
    }
}

src/Web/ColorMix.Web/Controllers/OrdersController.cs
using System;
using ColorMix.Services.DataServices.Contracts;
using ColorMix.Services.Models.Orders;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using ColorMix.Data.Models;
using ColorMix.Services.Models;
using Microsoft.AspNetCore.Identity;

namespace ColorMix.Web.Controllers
{
    [Authorize]
    public class OrdersController : BaseController
    {
        private readonly IUserService userService;
        private readonly ICartService cartService;
        private readonly IOrdersService ordersService;
        private readonly UserManager<ColorMixUser> userManager;

        public OrdersController(IUserService userService,
                                ICartService cartService,
                                IOrdersService ordersService,
                                UserManager<ColorMixUser> userManager)
        {
            this.userService = userService;
            this.cartService = cartService;
            this.ordersService = ordersService;
            this.userManager = userManager;
        }
        
        public IActionResult CheckoutAddress()
        {
            var userId = this.userManager.GetUserId(this.User);

            var userData = userService.GetUserData(userId);

            var viewModel = new OrdersViewModel()
            {
                FirstName = userData.FirstName,
                LastName = userData.LastName,
                Email = userData.Email,
                PhoneNumber = userData.PhoneNumber,
                AddressCity = userData.AddressCity,
                AddressCountry = userData.AddressCountry,
                AddressStreet = userData.AddressStreet,
                AddressZipCode = userData.AddressZipCode
            };

            return View(viewModel);
        }
        
        [HttpPost]
        public IActionResult OrderReview(OrdersViewModel model)
        {
            if (!ModelState.IsValid) return RedirectToAction("CheckoutAddress");

            var userId = this.userManager.GetUserId(this.User);

            var products = cartService.GetAllCartProducts(HttpContext.Session, userId);

            model.Products = products.ToList();

            return View(model);
        }
        
        [HttpPost]
        public IActionResult PlaceOrder(OrdersViewModel model)
        {
            if (!ModelState.IsValid) return RedirectToAction("OrderReview");

            var userId = this.userManager.GetUserId(this.User);

            var products = cartService.GetAllCartProducts(HttpContext.Session, userId);

            model.Products = products.ToList();

            ordersService.PlaceOrder(model, userId);

            return RedirectToAction("MyOrders", "Users");
        }
        
        public IActionResult Details(Guid id)
        {
            if (!this.ordersService.OrderExists(id))
            {
                return View("Error", new ErrorViewModel() { Message = ERROR });
            }

            var detailsModel = this.ordersService.GetOrderDetails(id);

            return this.View(detailsModel);
        }
    }
}

src/Web/ColorMix.Web/Views/Orders/CheckoutAddress.cshtml
@model OrdersViewModel

<div id="all">
    <div id="content">
        <div class="container mt-3">
            <div class="row">
                <div class="col-lg-3">
                    <partial name="_CustomerMenuPartial" />
                    <vc:Order-Summary></vc:Order-Summary>
                </div>
                <div id="checkout" class="col-lg-9">
                    <div class="box">
                        <form asp-controller="Orders" asp-action="OrderReview" method="post">
                            <h1>Адрес за доставка</h1>
                            <p class="text-muted">
                                Можете да коригирате данните за доставка от <a asp-controller="Users" asp-action="MyPersonalData">тук</a>.
                            </p>
                            <div class="nav flex-column flex-md-row nav-pills text-center">
                                <a href="checkout1.html" class="nav-link flex-sm-fill text-sm-center active"> <i class="fa fa-map-marker"> </i>Адрес</a>
                                <a href="#" class="nav-link flex-sm-fill text-sm-center disabled"> <i class="fa fa-eye"> </i>Преглед на поръчката</a>
                            </div>
                            <div class="content py-3">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="FirstName">Име<span class="text-danger">*</span></label>
                                            <input asp-for="FirstName" value="@Model.FirstName" class="form-control" readonly>
                                            <span asp-validation-for="FirstName" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="LastName">Фамилия<span class="text-danger">*</span></label>
                                            <input asp-for="LastName" value="@Model.LastName" class="form-control" readonly>
                                            <span asp-validation-for="LastName" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.row-->
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="AddressCountry">Държава<span class="text-danger">*</span></label>
                                            <input asp-for="AddressCountry" value="@Model.AddressCountry" class="form-control" readonly>
                                            <span asp-validation-for="AddressCountry" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="AddressCity">Град<span class="text-danger">*</span></label>
                                            <input asp-for="AddressCity" value="@Model.AddressCity" class="form-control" readonly>
                                            <span asp-validation-for="AddressCity" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.row-->
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="AddressZipCode">Пощенски код<span class="text-danger">*</span></label>
                                            <input asp-for="AddressZipCode" type="number" value="@Model.AddressZipCode" class="form-control" readonly>
                                            <span asp-validation-for="AddressZipCode" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="PhoneNumber">Телефонен номер<span class="text-danger">*</span></label>
                                            <input asp-for="PhoneNumber" value="@Model.PhoneNumber" class="form-control" readonly>
                                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="AddressStreet">Улица<span class="text-danger">*</span></label>
                                            <input asp-for="AddressStreet" value="@Model.AddressStreet" class="form-control" readonly>
                                            <span asp-validation-for="AddressStreet" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="Email">E-mail Адрес<span class="text-danger">*</span></label>
                                            <input asp-for="Email" value="@Model.Email" class="form-control" readonly>
                                            <span asp-validation-for="Email" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.row-->
                            </div>
                            <!-- /.content-->
                            <div class="box-footer d-flex justify-content-between">
                                <a asp-controller="Cart" asp-action="Index" class="btn btn-outline-secondary">
                                    <i class="fa fa-chevron-left"></i>Количка
                                </a>
                                <button type="submit" class="btn btn-primary">Напред<i class="fa fa-chevron-right"></i></button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box-->
                </div>
                <!-- /.col-lg-9-->
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

src/Web/ColorMix.Web/Views/Orders/Details.cshtml
@model OrderDetailsViewModel

<div id="all">
    <div id="content">
        <div class="container mt-3">
            <div class="row">
                <div class="col-lg-3">
                    <!--
                    *** CUSTOMER MENU ***
                    _________________________________________________________
                    -->
                    @if (this.User.IsInRole("Admin"))
                    {
                        <partial name="~/Areas/Administration/Views/Shared/_AdminMenuPartial.cshtml" />
                    }
                    else
                    {
                        <partial name="_CustomerMenuPartial" />
                    }
                    <!-- /.col-lg-3-->
                    <!-- *** CUSTOMER MENU END ***-->
                </div>
                <div id="customer-order" class="col-lg-9">
                    <div class="box">
                        <h1>Поръчка #@Model.OrderNumber</h1>
                        @if (this.User.IsInRole("User"))
                        {
                            <p class="text-muted">
                                Ако имате въпроси, <a asp-controller="Home" asp-action="Contacts">Свържете се с нас</a>
                            </p>
                            <hr>
                        }
                            <div class="table-responsive mb-4">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th colspan="2">Продукт</th>
                                            <th>Количество</th>
                                            <th>Размер</th>
                                            <th>Единична цена</th>
                                            <th>Общо</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var product in Model.Products)
                                        {
                                        <tr>
                                            <td><a href="#"><img src="@product.ImageUrl" alt="@product.Name"></a></td>
                                            <td><a asp-controller="Products" asp-action="Details" asp-route-id="@product.Id">@product.Name</a></td>
                                            <td>@product.Quantity</td>
                                            <td>@product.Size</td>
                                            <td>@product.UnitPrice лв.</td>
                                            <td>@product.TotalPrice лв.</td>
                                        </tr>
                                        }
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th colspan="5" class="text-right">Общо</th>
                                            <th>@Model.OrderTotalPrice</th>
                                        </tr>
                                    </tfoot>
                                </table>
                                @if (this.User.IsInRole("Admin") && Model.OrderStatus == OrderStatus.BeingPrepared)
                                {
                                    <div id="basket-overview" class="d-flex justify-content-end">
                                        <a asp-area="Administration" asp-controller="AdminOrders" asp-action="SendOrder" asp-route-orderId="@Model.Id" class="btn btn-primary navbar-btn"><i class="fas fa-sign-in-alt mr-1"></i><span>Изпрати</span></a>
                                    </div>
                                }
                            </div>
                        <!-- /.table-responsive-->
                        <div class="justify-content-end">
                            <h2>Адрес за доставка</h2>
                            <p>
                                @Model.Address.Receiver<br />
                                @Model.Address.Street<br>
                                @Model.Address.City, @Model.Address.ZipCode<br>
                                @Model.Address.Country<br>
                                @Model.Address.PhoneNumber
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/Web/ColorMix.Web/Views/Orders/OrderReview.cshtml
@model OrdersViewModel
@{
    var totalPrice = Model.Products.Sum(x => x.Total);
}

<div id="all">
    <div id="content">
        <div class="container mt-3">
            <div class="row">
                <div class="col-lg-3">

                    <partial name="_CustomerMenuPartial" />
                    <vc:Order-Summary></vc:Order-Summary>
                </div>
                <div id="checkout" class="col-lg-9">
                    <div class="box">
                        <form asp-controller="Orders" asp-action="PlaceOrder" method="post">
                            <h1>Преглед на поръчката</h1>
                            <div class="nav flex-column flex-sm-row nav-pills">
                                <a asp-controller="Orders" asp-action="CheckoutAddress" class="nav-link flex-sm-fill text-sm-center"> <i class="fa fa-map-marker"> </i>Адрес</a>
                                <a href="#" class="nav-link flex-sm-fill text-sm-center active"> <i class="fa fa-eye"> </i>Преглед на поръчката</a>
                            </div>
                            <div class="content">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th colspan="2">Продукт</th>
                                                <th>Количество</th>
                                                <th>Размер</th>
                                                <th>Единична цена</th>
                                                <th>Общо</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var product in Model.Products)
                                            {
                                                <tr>
                                                    <td>
                                                        <a href="#">
                                                            <img src="@product.ImageUrl" alt="@product.Name">
                                                        </a>
                                                    </td>
                                                    <td><a asp-controller="Products" asp-action="Details" asp-route-id="@product.Id">@product.Name</a></td>
                                                    <td>
                                                        @product.Quantity
                                                    </td>
                                                    <td>
                                                        @product.Size
                                                    </td>
                                                    <td>
                                                        @product.Price
                                                    </td>
                                                    <td>
                                                        @product.Total лв.
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th colspan="5">Общо</th>
                                                <th>@totalPrice лв.</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                                <!-- /.table-responsive-->
                            </div>
                            <!-- /.content-->
                            <div class="box-footer d-flex justify-content-between">
                                <a asp-controller="Orders" asp-action="CheckoutAddress" class="btn btn-outline-secondary"><i class="fa fa-chevron-left"></i>Назад</a>
                                <button type="submit" class="btn btn-primary">Поръчай<i class="fa fa-chevron-right"></i></button>
                            </div>

                            <input asp-for="AddressCity" type="hidden" />
                            <input asp-for="AddressCountry" type="hidden" />
                            <input asp-for="Products" type="hidden" />
                            <input asp-for="AddressStreet" type="hidden" />
                            <input asp-for="AddressZipCode" type="hidden" />
                            <input asp-for="Email" type="hidden" />
                            <input asp-for="FirstName" type="hidden" />
                            <input asp-for="LastName" type="hidden" />
                            <input asp-for="PhoneNumber" type="hidden" />
                        </form>
                    </div>
                    <!-- /.box-->
                </div>
                <!-- /.col-lg-9-->
            </div>
        </div>
    </div>
</div>