src/Web/ColorMix.Web/Areas/Administration/Controllers/AdminCategoriesController.cs
using System.Linq;
using ColorMix.Services.DataServices.Contracts;
using ColorMix.Services.Models.Categories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ColorMix.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    [Authorize(Roles = "Admin")]
    public class AdminCategoriesController : AdminController
    {
        private readonly ICategoryService categoryService;

        public AdminCategoriesController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public IActionResult CreateCategory()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult CreateCategory(CreateCategoryViewModel model)
        {
            if (!ModelState.IsValid) return this.View(model);

            this.categoryService.CreateCategory(model);

            return this.RedirectToAction("Index", "Home");
        }

        public IActionResult CreateSubCategory()
        {
            var categoryData = this.categoryService.GetAllCategoriesAndSubCategories();

            this.ViewData["Categories"] = categoryData.Select(x => x.Name).ToList();

            return this.View();
        }

        [HttpPost]
        public IActionResult CreateSubCategory(CreateCategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var categoryData = this.categoryService.GetAllCategoriesAndSubCategories();

                this.ViewData["Categories"] = categoryData.Select(x => x.Name).ToList();

                return this.View(model);
            }
            
            this.categoryService.CreateSubCategory(model);

            return this.RedirectToAction("Index", "Home");
        }
    }
}

src/Web/ColorMix.Web/Areas/Administration/Views/AdminCategories/CreateCategory.cshtml
@model CreateCategoryViewModel

<div id="all">
    <div id="content">
        <div class="container mt-3 mb-3">
            <div class="row">
                <div class="col-lg-3">
                    <!--Customer meu-->
                    <partial name="~/Areas/Administration/Views/Shared/_AdminMenuPartial.cshtml" />
                    <!--Customer menu end-->
                </div>
                <div class="col-lg-9">
                    <div class="box">
                        <h1>Създаване на нова категория</h1>
                        <form asp-area="Administration" asp-controller="AdminCategories" asp-action="CreateCategory"method="post">
                            <div class="form-row">
                                <div class="col">
                                    <label asp-for="@Model.CategoryName">Име на категорията<span class="text-danger">*</span></label>
                                    <input asp-for="@Model.CategoryName" class="form-control" placeholder="Име на категорията" />
                                    <span asp-validation-for="@Model.CategoryName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col">
                                    <label asp-for="@Model.SubCаtegoryNames">Имена на подкатегории<span class="text-danger">*</span></label>
                                    <input asp-for="@Model.SubCаtegoryNames" class="form-control" placeholder="Въведете имена на подкатегории, разделени със запетая" />
                                    <span asp-validation-for="@Model.SubCаtegoryNames" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="text-center mt-3">
                                <button type="submit" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Създай</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

src/Web/ColorMix.Web/Areas/Administration/Views/AdminCategories/CreateSubCategory.cshtml
@model CreateCategoryViewModel

<div id="all">
    <div id="content">
        <div class="container mt-3 mb-3">
            <div class="row">
                <div class="col-lg-3">
                    <!--Customer meu-->
                    <partial name="~/Areas/Administration/Views/Shared/_AdminMenuPartial.cshtml" />
                    <!--Customer menu end-->
                </div>
                <div class="col-lg-9">
                    <div class="box">
                        <h1>Създаване на нова категория</h1>
                        <form asp-area="Administration" asp-controller="AdminCategories" asp-action="CreateSubCategory" method="post">
                            <div class="form-row">
                                <div class="col">
                                    <select asp-for="@Model.CategoryName" class="form-control"
                                            asp-items="@(new SelectList((IEnumerable<string>)this.ViewData["Categories"]))">
                                        <option>Име на категория</option>
                                    </select>
                                    <span asp-validation-for="@Model.CategoryName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col">
                                    <label asp-for="@Model.SubCаtegoryNames">Имена на подкатегории<span class="text-danger">*</span></label>
                                    <input asp-for="@Model.SubCаtegoryNames" class="form-control" placeholder="Въведете имена на подкатегории, разделени със запетая" />
                                    <span asp-validation-for="@Model.SubCаtegoryNames" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="text-center mt-3">
                                <button type="submit" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Създай</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}