src/Web/ColorMix.Web/Controllers/CartController.cs
using System;
using ColorMix.Data.Models;
using ColorMix.Services.DataServices.Contracts;
using ColorMix.Services.Models;
using ColorMix.Services.Models.Products;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ColorMix.Web.Controllers
{
    public class CartController : BaseController
    {
        private readonly ICartService cartService;
        private readonly IProductService productService;
        private readonly UserManager<ColorMixUser> userManager;

        public CartController(ICartService cartService, IProductService productService, UserManager<ColorMixUser> userManager)
        {
            this.cartService = cartService;
            this.productService = productService;
            this.userManager = userManager;
        }
        
        public IActionResult Index()
        {
            var userId = this.userManager.GetUserId(this.User);

            var products = this.cartService.GetAllCartProducts(this.HttpContext.Session, userId);

            return this.View(products);
        }

        [HttpPost]
        public IActionResult AddToCart(DetailsViewModel model)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, ERROR);

                return this.RedirectToAction("Details", "Products");
            }

            this.cartService.AddToCart(model, this.HttpContext.Session, userId);

            return this.RedirectToAction("Index");
        }

        public IActionResult Remove(Guid id)
        {
            if (!this.productService.CheckIfProductExists(id))
            {
                return View("Error", new ErrorViewModel() { Message = ERROR });
            }
            
            this.cartService.Remove(id, this.HttpContext.Session, this.User);
            
            return this.RedirectToAction("Index");
        }
    }
}

src/Web/ColorMix.Web/Controllers/UsersController.cs
using System.Linq;
using ColorMix.Data.Models;
using ColorMix.Services.DataServices.Contracts;
using ColorMix.Services.Models.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ColorMix.Web.Controllers
{
    [Authorize]
    public class UsersController : BaseController
    {
        private readonly IUserService userService;
        private readonly IOrdersService ordersService;
        private readonly UserManager<ColorMixUser> userManager;
        
        public UsersController(IUserService userService, 
                               IOrdersService ordersService, UserManager<ColorMixUser> userManager)
        {
            this.userService = userService;
            this.ordersService = ordersService;
            this.userManager = userManager;
        }
        
        public IActionResult MyOrders()
        {
            var userId = this.userManager.GetUserId(this.User);

            var orders = this.ordersService.GetUserOrders(userId).ToList();

            return View(orders);
        }
        
        public IActionResult MyPersonalData()
        {
            var userId = this.userManager.GetUserId(this.User);

            var profileData = this.userService.GetUserData(userId);

            return View(profileData);
        }

        [HttpPost]
        public IActionResult ChangePersonalData(ProfileDataViewModel model)
        {
            if (!ModelState.IsValid) return RedirectToAction("MyPersonalData");

            var userId = this.userManager.GetUserId(this.User);

            this.userService.ChangeUserData(userId, model);

            return RedirectToAction("MyPersonalData");
        }
    }
}

src/Web/ColorMix.Web/Views/Shared/Components/Menu/Default.cshtml
@model IEnumerable<CategoryViewModel>

<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <a asp-controller="Home" asp-action="Index" class="navbar-brand home"><img src="/img/logo.png" alt="Obaju logo" class="d-none d-md-inline-block"><img src="img/logo-small.png" alt="Obaju logo" class="d-inline-block d-md-none"><span class="sr-only">Obaju - go to homepageNumber</span></a>
        <div id="navigation" class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a asp-controller="Home" asp-action="Index" class="nav-link active">Начало</a>
                </li>
                @foreach (var menuItem in Model)
                {
                    <li class="nav-item dropdown menu-large">
                        <a asp-controller="Products" asp-action="ProductsByCategory" asp-route-categoryId="@menuItem.Id" data-delay="200" class="nav-link">@menuItem.Name</a>
                    </li>
                }
            </ul>

            <!--Shopping Cart-->
            <div class="navbar-buttons d-flex justify-content-end">
                <!-- /.nav-collapse-->
                @if (!this.User.Identity.IsAuthenticated)
                {
                    <div id="basket-overview" class="d-lg-block"><a asp-area="Identity" asp-page="/Account/Login" class="btn btn-primary navbar-btn"><i class="fas fa-sign-in-alt mr-1"></i><span>Вход</span></a></div>
                    <div id="basket-overview" class="d-lg-block"><a asp-area="Identity" asp-page="/Account/Register" class="btn btn-primary navbar-btn"><i class="fas fa-user-plus mr-1"></i><span>Регистрация</span></a></div>
                    <div id="basket-overview" class="d-lg-block"><a asp-controller="Home" asp-action="Contacts" class="btn btn-primary navbar-btn"><i class="far fa-comments mr-1"></i><span>Контакти</span></a></div>
                }

                @if (this.User.Identity.IsAuthenticated && !this.User.IsInRole("Admin"))
                {
                    <div id="basket-overview" class="d-lg-block"><a asp-controller="Home" asp-action="Contacts" class="btn btn-primary navbar-btn"><i class="far fa-comments mr-1"></i><span>Контакти</span></a></div>
                }

                <div id="basket-overview" class="navbar-collapse collapse d-none d-lg-block">
                    <a asp-controller="Cart" asp-action="Index" class="btn btn-primary navbar-btn"><i class="fa fa-shopping-cart"></i><span>Количка</span></a>
                </div>

                @if (this.User.Identity.IsAuthenticated)
                {
                    <div id="basket-overview" class="d-lg-block"><a asp-controller="Users" asp-action="MyPersonalData" class="btn btn-primary navbar-btn"><i class="fas fa-user mr-1"></i><span>Профил</span></a></div>

                    <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })" method="post">

                        <button type="submit" class="btn btn-primary mr-2"> <i class="fas fa-sign-out-alt mr-1"></i> Излез</button>
                    </form>
                }
            </div>
        </div>
    </div>
</nav>